### ISSUE TITLE
generated header guards missing path to file

### ISSUE THREAD

**Issue by Michaelhobo** [Embedded-AMS/EmbeddedProto#10]
The header guard still isn't correct, in a different (better...) way than https://github.com/Embedded-AMS/EmbeddedProto/issues/6

With a proto file at a/b/c.h, I expected header guards to include the path. Now, only the filename is used.

Expected: _A_B_C_H_
Got: _C_H_

This means if you have two proto files in different directories with the same name, the header guards will collide.

**Comment by BartHertog** [comment]
Done
