### ISSUE TITLE
Optional fields support

### ISSUE THREAD

**Issue by DenDasus** [Embedded-AMS/EmbeddedProto#16]
Hello!

Please, add optional fields support in proto3 syntax. This implemented by **--experimental_allow_proto3_optional** protoc flag. This feature will be added to protoc soon, but now it is experimental.

Error string: _Api.proto: is a proto3 file that contains optional fields, but code generator protoc-gen-eams hasn't been updated to support optional fields in proto3. Please ask the owner of this code generator to support proto3 optional._

**Comment by BartHertog** [comment]
Hello DanDasus,

I will look into this. It is an extensive request as far as I can see now. All fields should get a boolean and function to get the boolean which indicates if the value has been set. However I do have felt the need for this from time to time when using proto3.

**Comment by BartHertog** [comment]
Work on this ticket has started.

**Comment by BartHertog** [comment]
The feature has been implemented. As of Embedded Proto version 2.3.0 it is possible to use the optional keyword in proto files. Please remember to use the proper protoc version.
