### ISSUE TITLE
Trouble getting venv to work on Ubuntu 18.04

### ISSUE THREAD

**Issue by Michaelhobo** [Embedded-AMS/EmbeddedProto#2]
Setup steps:
Installed python3, pip, venv, protobuf, git, cmake, etc.
Ran setup.sh script

Problem:
All paths in protoc-gen-eams are relative. When generating protos from a different directory, these paths all fail to resolve.  

Solution:
Add $(dirname $0) in front of both ./venv/bin/python and generator/protoc-gen-eams.py

**Comment by sgerbino** [comment]
It would be nice to leverage `protoc-gen-eams` from an external directory (e.g. when utilizing the CMake macro `protobuf_generate`).

**Comment by BartHertog** [comment]
@sgerbino It is likely we will pick this up with a next minor release.

**Comment by BartHertog** [comment]
@Michaelhobo Dirname has been implemented. Sorry for this long delay in this simple ticket.

**Comment by BartHertog** [comment]
@sgerbino Implemented the dirname solution. It is in develop, I have not tested it with `protobuf_generate`, will you let me know it it works for you?

**Comment by BartHertog** [comment]
@Michaelhobo @sgerbino It is now in version 2.3.2

**Comment by sgerbino** [comment]
I'm currently used a hacked up version of your fixes in 2.x and 3.0 release here: https://github.com/koinos/EmbeddedProto

I won't be able to test it out until the 3.0 release @BartHertog

Thanks for this update, I will let you know as soon as it's available in the 3.0 version

**Comment by BartHertog** [comment]
@sgerbino I will merge the current 2.x state in to the release candidate branch probably in the coming week.
