### ISSUE TITLE
Failure when importing descriptor.proto

### ISSUE THREAD

**Issue by mvandeberg** [Embedded-AMS/EmbeddedProto#25]
I am adding a custom option via extending `google.protobuf.FieldOptions` and am getting the following error:

`--eams_out: Embedded Proto error - Messages with repeated, string or byte fields use template parameters to define their length.For some reason it was not to add all required template parameters.`

Here is a minimal reproducible case:

```proto
syntax = "proto3";

import "google/protobuf/descriptor.proto";

enum my_enum {
   ENUM_A = 0;
   ENUM_B = 1;
}

extend google.protobuf.FieldOptions {
   optional my_enum my_enum_option = 50000;
}
```

Adding `import "google/protobuf/descriptor.proto";` on its own is enough to cause the failure.

I do not need the option available in EmbeddedProto generated code, but I do need it in other generated languages. I just need EmbeddedProto to not fail generation on this input.

**Comment by BartHertog** [comment]
Hello @mvandeberg,

Just pushed this ticket to develop. A sorting algorithms has been added to solve simple inclusions and the message order. It is tested with the case you supplied.

Let me know if you have any remarks.

Best regards,

Bart
