### ISSUE TITLE
ReadBufferInterface interface

### ISSUE THREAD

**Issue by jchia** [Embedded-AMS/EmbeddedProto#29]
Both overloads of `advance()` return void and so have no way to report an error condition, in particular, end-of-input.

Since in the recent commit a0819ae57fe440518d783c4779e52297f8e3d06e `advance()` started to actually be used, this commit is when the problem starts to be real.

The practical problem all this results in right now is that when skipping an unknown length-delimited field, you could skip pass the end-of-input without realizing it.

There is also the question of what to do when the number of remaining bytes is less than the requested number of bytes, whether to not advance at all or advance to the end anyway.

**Comment by BartHertog** [comment]
Hello @jchia,

Valid point. The class will be modified to return an error. 
It is a potential code breaker for current users. For this reason it will probably be released on the 3.0.0 release candidate branch.

Best regards,

Bart

**Comment by BartHertog** [comment]
Hello @jchia,

In the rc-3.0.0 branch the advance() functions have been modified to include a return boolean. In the develop branch a deprecated warning has been added.

Best regards,
Bart
