### ISSUE TITLE
RepeatedField.h won't compile in ARM6 compiler

### ISSUE THREAD

**Issue by DavidHammond123** [Embedded-AMS/EmbeddedProto#37]
The ARM6 compiler is not happy with this struct definition and static_assert in RepeatedField.h:

    //! Definition of a trait to check if DATA_TYPE is or is not a specialization of the FieldTemplate.
    template<typename T>
    static constexpr auto is_specialization_of_FieldTemplate_v = is_specialization_of_FieldTemplate<T>::value;

    //! This class only supports Field and FieldTemplate classes as template parameter.
    static_assert(std::is_base_of_v<::EmbeddedProto::Field, DATA_TYPE> || is_specialization_of_FieldTemplate_v<DATA_TYPE>, 
                  "A Field can only be used as template parameter.");

It does not like having to cast is_specialization_of_FieldTemplate_v from auto to bool in the static_assert.
I fixed this by changing the type of is_specialization_of_FieldTemplate_v to bool from auto.

I'm not super confident in what exactly is going on in this code so I didn't want to make a PR but that is how I fixed it.

(So my new definition is:
    //! Definition of a trait to check if DATA_TYPE is or is not a specialization of the FieldTemplate.
    template<typename T>
    static constexpr bool is_specialization_of_FieldTemplate_v = is_specialization_of_FieldTemplate<T>::value;
)

**Comment by BartHertog** [comment]
Hello David, 

Thanks for writing in. We will be looking into this. I can imagine that this is compiler specific. I would have to look into why your specification would work without the template typename T defined.

Best regards,

Bart

**Comment by BartHertog** [comment]
A clear! Will use that when testing.

**Comment by DavidHammond123** [comment]
And this is the actual error message that comes out:
`../../../core-code/protocol-buffers/embedded_proto/src\RepeatedFieldFixedSize.h(34): warning: In file included from...
../../../core-code/protocol-buffers/embedded_proto/src/RepeatedField.h(66): error: value of type 'const auto' is not contextually convertible to 'bool'
    static_assert(std::is_base_of_v<::EmbeddedProto::Field, DATA_TYPE> || is_specialization_of_FieldTemplate_v<DATA_TYPE>, `

**Comment by BartHertog** [comment]
Your change works just fine with GCC. The unit tests pass without issues. Your welcome to make the PR. Please do this from develop to develop.

**Comment by BartHertog** [comment]
Hello @DavidHammond123,

Your solution to this problem has been included as of release 3.0.1. Thank you for the suggestion!

Best regards,

Bart
