### ISSUE TITLE
Optimize `oneof`

### ISSUE THREAD

**Issue by darkdragon-001** [Embedded-AMS/EmbeddedProto#44]
Is it really necessary to clear to contents of the field when clearing the `oneof`:

https://github.com/Embedded-AMS/EmbeddedProto/blob/7ea7b8ba3f089e8f474508e9007746f312521578/generator/templates/TypeOneof.h#L97

or might it be enough to leave whatever data is in there as it will be overwritten by the next `set()` operation before this field can be used again anyways (maybe we have to move the `clear()` call in the `set()` call when it is not guaranteed that everything will be overwritten by the next `set()` call). Especially for large `byte` fields (e.g. in the range kilobytes) this might have a big performance impact on embedded devices!

**Comment by BartHertog** [comment]
Hello @darkdragon-001,

Thank you for your efforts to improve Embedded Proto! I need some time to review both this optimization and your pull requests. I will keep you posted.

Best regards,

Bart

**Comment by BartHertog** [comment]
Hello @darkdragon-001,

Can you elaborate a bit more on when this will give a performance improvement? Will this not just move the performance cost from one function to the other? 

Best regards,

Bart

**Comment by darkdragon-001** [comment]
Using a different field in the `oneof` will be faster as it doesn't need to clean other fields. Furthermore, if we can overwrite on the next `set()` without ever clearing, this will always save us the time to clear.

**Comment by BartHertog** [comment]
I think it does need cleaning. There is something about objects in unions that need destruction before you can use the union again. That is why I believe it is just moving the execution cycles from one function to another. I can not fully recall now. I am going to look it up.

**Comment by darkdragon-001** [comment]
Oh you are using `union`s for the `oneof`s? Then I guess you are right and the destructor [must be called explicitely](https://en.cppreference.com/w/cpp/language/union#Explanation). I will try to assemble a minimum example with our problem such that we can work out another approach together to work around this problem.

**Comment by BartHertog** [comment]
Try making the unit tests. In the folder `build/eams` you will find generated code for messages with oneof's.

**Comment by darkdragon-001** [comment]
I was checking the code and found some optimizations for large byte/string fields as suggested in #47.

**Comment by BartHertog** [comment]
I got the feeling you got a really particular performance issue. Would you like to discuss this in private?
