### ISSUE TITLE
template parameters not generated when including message in a different file, same package

### ISSUE THREAD

**Issue by Michaelhobo** [Embedded-AMS/EmbeddedProto#5]
I have 2 files, example.proto and example2.proto

example.proto:
```proto
package a.b;
import "path/to/example2.proto";
message X {
  X2 val = 1;
}
```

example2.proto: 
```proto
package a.b;
message X2 {
  repeated int32 list = 1;
}
```

class X's val return value doesn't have the template parameters for list's length.

If I remove `package a.b;` from both files, it works correctly.

**Comment by BartHertog** [comment]
This was solved in internal ticket PROTO-57. When searching for messages with templates the namespace (package) was not correctly included, thus no match was found. This resulted in skipping the addition of the template.
