### ISSUE TITLE
Expose mutable string and byte buffer and the set_length API

### ISSUE THREAD

**Issue by wuyuanyi135** [Embedded-AMS/EmbeddedProto#51]
Currently, to assign the elements in a string or a byte buffer field, one must either use `operator[]` or `operator=`. 

However, it is common in embedded world to assign the raw buffer with `memcpy`, `str(n)cpy`, `s(n)printf`, etc. We have to allocate another temporary buffer to contain the data, then copy to the message buffer. This causes memory usage bloating by a factor of two.

By exposing the mutable (no const qualifier) access to the internal buffer, the intermediate buffer is no longer required, hence saving memory.

In the current API, the mutable pointer could be accessed with `&message[0]`. However, after copying operation, the field size cannot be updated because the `set_length` api is private.

I suggest to expose the `set_length` API for the sake of the application using the string/byte internal buffer directly.

**Comment by BartHertog** [comment]
I have no problem doing that. Do mind to copy the null terminator for a but exclude it from the length.

As an alternative, you can use the function `Error set(const DATA_TYPE* data, const uint32_t length)` which will copy the data for you.

What is in the backlog is to start using the C++17 std::string_view class. This could be done in two directions. One in which the message object still owns the data but just uses the string_view class in it's function calls. The second is where the message object does not own the data and has a std::string_view object to access the data held externally.
