### ISSUE TITLE
header guards generated with "/" instead of "_", not ISO C++11 compliant

### ISSUE THREAD

**Issue by Michaelhobo** [Embedded-AMS/EmbeddedProto#6]
GCC complains:
example.h:33:9: warning: ISO C++11 requires whitespace after the macro name
   33 | #define _A/B/PROTO/EXAMPLE_H_

Why are the header guards generated with "/" in them instead of "_"?

**Comment by BartHertog** [comment]
This issue is fixed in our internal ticket PROTO-58 and will be pushed to github in the coming days.
