### ISSUE TITLE
Setup script fails with protoc minor updates

### ISSUE THREAD

**Issue by andewx** [Embedded-AMS/EmbeddedProto#64]
The setup script seems to fail comparing protoc versions with required versions.

We attempt a regular expression parse <major>.<minor>.<patch>

However the script fails comparing minor updates and it is now on the user to ensure compatibility

Original script fails with:

```
The version of Protoc (v0.None) you have installed is not compatible with the version of
the protobuf python package (v21.6) Embedded Proto requires. These are your options:
	1. Install a matching version of Protoc.
	2. Change the version of Embedded Proto.
```

First of all inherently minor updates to API's should not be considered API breaking, I find it odd that we have to version control our protoc to match the EmbeddedProto tool without any leniency.

Also `protoc --versions` apperars to only output `24.0` <minor>.<patch>

User is required to update the available protobuf versions and ensure compatibility with the read protoc version.

FIX: User can update the script themselves and approve minor versions up to their installed version. In this case '24.0'

---------------------------------------------------------

Solution: 

Issue warning only for minor version incompatibility updates to protobuf. It seems odd to restrict the protoc minor version updates, perhaps there needs to be a CI process in place that is subordinate to the protobuf schedule as well.

**Comment by BartHertog** [comment]
My apologies for the delay in response. This might be related to an issue solved in the development branch. Could you try this?
