### ISSUE TITLE
Improve Protoc version handling

### ISSUE THREAD

**Issue by IronJulo** [Embedded-AMS/EmbeddedProto#67]
## Issue Description

The current implementation assumes that Protobuf version always defines a major version, but there are cases where the major version may not always be present. As a result, the existing regular expression captures the minor number as the major and the patch number as the minor.

## Existing Modifications

There have been prior attempts to handle this issue, but they do not seem to provide a reliable solution.

## Context

**Embedded Proto Version:** 3.3.2

## Expected Behavior

When encountering Protobuf versions without a major version, the version handling should correctly identify and capture major, minor, and patch numbers.

## Observed Behavior

The script setup.py doesn't correctly identify and capture major, minor, and patch numbers.

## Steps to Reproduce

1. Encounter a Protobuf version without a major version (e.g., "libprotoc 25.0").
2. Try to use the setup.py script.

**Comment by BartHertog** [comment]
The issue has been resolved in #68. Thank you for your input.
