### ISSUE TITLE
RepeatedFieldFixedSize.h compares signed and unsigned integers in get_const()

### ISSUE THREAD

**Issue by kcsoftwaredev** [Embedded-AMS/EmbeddedProto#69]
The index argument to get_const() within RepeatedFieldFixedSize.h is a signed integer and it is being compared to an unsigned integer.  This causes compiler warnings.  Updating the 'index' argument to be 'const uint32_t' resolves this.  Additionally, the index argument is an index into an array; if a negative value is passed in, then the range check against the current length will still pass and result in data corruption.

**Comment by BartHertog** [comment]
True. Fixed and available in the development branch.
