### ISSUE TITLE
Protoc plugin not working on Windows with space in path

### ISSUE THREAD

**Issue by moritz-geier** [Embedded-AMS/EmbeddedProto#74]
When i try to use the plugin supplied by you with a space in the path, e.g `C:\Path to\protoc-gen-eams.bat`, then the compilation doesn't work.

## Proposed solution
Change in protoc-gen-eams.bat line
```
%EmbeddedProtoDir%\venv\Scripts\protoc-gen-eams
```
to
```
call "%EmbeddedProtoDir%\venv\Scripts\protoc-gen-eams"
```

**Comment by BartHertog** [comment]
Hello @moritz-geier,

Thank you for writing in and proposing this solution. It has been implemented on the development branch. 

Please note there is a change on the development branch which in some cases be a small breaking change for you. This is the case when you have derived your own classes from the RepeatedField class.

Thanks for your input.

Best regards,

Bart
