### ISSUE TITLE
Add protobuf-compiler package to kpi

### ISSUE THREAD

**Issue by wcravens** [Embedded-AMS/EmbeddedProto#80]

**Comment by BartHertog** [comment]
Hello @wcravens,

Thank you for writing in. Can you elaborate on what you mean by adding the protobuf-compiler package to KPI? I am not aware of the abbreviation KPI in these contexts.

Best regards,

Bart

**Comment by wcravens** [comment]
My apologies.  This can be ignored/closed.  It was meant for my project repository.  Accidentally created here using gh cli.
